run: vector_insert
	./vector_insert
vector_insert: vector_insert.cpp
	g++ -o vector_insert vector_insert.cpp -std=c++2a
vector_end: vector_end.cpp
	g++ -o vector_end vector_end.cpp -std=c++2a 
itr:	vector_itr.cpp
	g++ -o itr vector_itr.cpp -std=c++2a

